In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch
print(torch.__version__)

2.1.0+cu121


## Introduction to Tensors

### Creating tensors

#### **scalar**


In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.shape

torch.Size([])

In [5]:
# Get tensor back as Python int

scalar.item()

7

#### **Vector**

In [6]:
vector1 = torch.tensor([7])
vector1

tensor([7])

In [7]:
vector1.ndim

1

In [8]:
vector1.shape # [how_many_scalar]

torch.Size([1])

In [9]:
vector = torch.tensor([7,7])

In [10]:
vector.ndim

1

In [11]:
vector.shape # [how_many_scalar]

torch.Size([2])

#### **MATRIX**

In [19]:
MATRIX = torch.tensor([[7,8],
                      [9,10],
                       [5,7]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10],
        [ 5,  7]])

In [20]:
MATRIX.ndim

2

In [21]:
MATRIX.shape # [row, column]  /  [how_many_VECTOR, scalar_in_each_VECTOR]

torch.Size([3, 2])

In [22]:
MATRIX[0] # is a vector

tensor([7, 8])

In [23]:
MATRIX[0].shape

torch.Size([2])

### **TENSOR**

In [45]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [46]:
TENSOR.ndim

3

In [47]:
TENSOR.shape # [how_many_MATRIX, each_MATRIX_row, each_MATRIX_column]

torch.Size([1, 3, 3])

In [48]:
TENSOR1 = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]],
                       [[4, 2, 3],
                        [3, 3, 9],
                        [2, 4, 6]]])
TENSOR1

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]],

        [[4, 2, 3],
         [3, 3, 9],
         [2, 4, 6]]])

In [49]:
TENSOR1.ndim

3

In [50]:
TENSOR1.shape # [how_many_MATRIX, each_MATRIX_row, each_MATRIX_column]

torch.Size([2, 3, 3])

In [51]:
TENSOR2 = torch.tensor([[[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]],
                       [[4, 2, 3],
                        [3, 3, 9],
                        [2, 4, 6]]],

                        [[[9, 2, 3],
                        [3, 4, 9],
                        [2, 4, 5]],
                       [[4, 9, 3],
                        [3, 5, 9],
                        [2, 4, 6]]]])
TENSOR2

tensor([[[[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]],

         [[4, 2, 3],
          [3, 3, 9],
          [2, 4, 6]]],


        [[[9, 2, 3],
          [3, 4, 9],
          [2, 4, 5]],

         [[4, 9, 3],
          [3, 5, 9],
          [2, 4, 6]]]])

In [52]:
TENSOR2.ndim

4

In [53]:
TENSOR2.shape # [how_many_TENSOR, how_many_MATRIX_in_each_TENSOR, each_MATRIX_row, each_MATRIX_column]

torch.Size([2, 2, 3, 3])

`scalar(ndim=0) --> vector(ndim=1) --> MATRIX(ndim=2) --> TENSOR(ndim=3)`

## Random tensors

* *Why random tensors?*
 > **Random tensors** are important beacause the way many Neural Networks learn is that, it **starts with some random tensors full of random weights (numbers)** and then adjust those random weights to better represent the data.  

In [54]:
random_tensor_1 = torch.rand(3)
random_tensor_1

tensor([0.4283, 0.7546, 0.6662])

In [55]:
random_tensor_1.ndim

1

In [57]:
random_tensor_2 = torch.rand(3,2)
random_tensor_2

tensor([[0.1016, 0.9429],
        [0.2772, 0.0148],
        [0.9530, 0.7743]])

In [59]:
random_tensor_2.ndim

2

In [60]:
random_tensor_3 = torch.rand(4,3,2)
random_tensor_3

tensor([[[0.9579, 0.6810],
         [0.5618, 0.2044],
         [0.7649, 0.3382]],

        [[0.9313, 0.6116],
         [0.9592, 0.8928],
         [0.3563, 0.8729]],

        [[0.1800, 0.4707],
         [0.3408, 0.3912],
         [0.1212, 0.3679]],

        [[0.6863, 0.6298],
         [0.6323, 0.0939],
         [0.5588, 0.9364]]])

In [61]:
random_tensor_3.ndim

3

In [62]:
random_tensor_4 = torch.rand(3,4,3,2)
random_tensor_4

tensor([[[[0.0902, 0.3723],
          [0.7999, 0.4377],
          [0.7548, 0.5889]],

         [[0.1601, 0.6627],
          [0.7116, 0.5490],
          [0.8396, 0.2663]],

         [[0.9843, 0.1575],
          [0.0103, 0.0711],
          [0.2055, 0.7109]],

         [[0.6322, 0.9943],
          [0.3999, 0.7933],
          [0.1523, 0.7513]]],


        [[[0.1440, 0.1481],
          [0.5654, 0.3729],
          [0.3387, 0.9677]],

         [[0.3093, 0.8628],
          [0.8883, 0.3007],
          [0.6202, 0.5984]],

         [[0.5749, 0.8798],
          [0.4117, 0.8703],
          [0.4038, 0.0709]],

         [[0.5285, 0.0745],
          [0.1308, 0.8680],
          [0.0662, 0.8638]]],


        [[[0.3035, 0.5071],
          [0.8880, 0.2168],
          [0.9182, 0.9522]],

         [[0.1448, 0.9009],
          [0.9130, 0.2549],
          [0.3374, 0.1691]],

         [[0.5699, 0.0268],
          [0.3037, 0.3174],
          [0.1815, 0.3506]],

         [[0.1283, 0.4810],
          [0.9848, 0.5

In [64]:
random_tensor_4.ndim

4